services:
  edge-nginx:
    image: nginx:stable
    container_name: edge-nginx
    restart: unless-stopped
    env_file:
      - .env.edge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./edge/templates:/etc/nginx/templates:ro
      - ./edge/acme:/var/www/certbot
      # odblokujesz po certach:
      - ./edge/certs:/etc/nginx/certs:ro
    networks:
      - trading-edge

networks:
  trading-edge:
    name: trading-edge
    external: true